// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace N8General
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidN8GeneralPkgString = "27dd9dea-6dd2-403e-929d-3ff20d896c5e";
        public const string guidN8GeneralCmdSetString = "32af8a17-bbbc-4c56-877e-fc6c6575a8cf";
        public static Guid guidN8GeneralPkg = new Guid(guidN8GeneralPkgString);
        public static Guid guidN8GeneralCmdSet = new Guid(guidN8GeneralCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidMyCommand = 0x0100;
    }
}
